最新のpipenv向けにPipfile.lockを更新
pipenv install 実行時に次のようなエラーが出る問題が修正されます。

      File "/usr/local/lib/python3.7/site-packages/pipenv/vendor/plette/models/sections.py", line 68, in validate
        super(Meta, cls).validate(data)
      File "/usr/local/lib/python3.7/site-packages/pipenv/vendor/plette/models/base.py", line 67, in validate
        return validate(cls, data)
      File "/usr/local/lib/python3.7/site-packages/pipenv/vendor/requirementslib/models/pipfile.py", line 59, in validate
        raise plette.models.base.ValidationError(data, v)
    plette.models.base.ValidationError: {'hash': {'sha256': '6b31e0033daa79d1024358ed94684438245566c82688ee72bb25934e76205331'}, 'requires': {}, 'sources': [{'url': 'https://pypi.python.org/simple', 'verify_ssl': True, 'name': 'pypi.python.org'}]}